name:                chards
version:             0.1.0.0
github:              "Garmelon/chards"
license:             BSD3
author:              "Joscha Mennicken"
maintainer:          "joscha@migejolise.de"
copyright:           "Joscha Mennicken"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A simple flashcard-based learning program.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Garmelon/chards#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- time
- transformers
- haskeline
- megaparsec
- random
- random-shuffle

library:
  source-dirs: src

executables:
  chards:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chards

tests:
  chards-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chards
